#!/usr/bin/env bash
set -euo pipefail

DATA_ROOT=${DATA_ROOT:-/data/liang.zhang/dataset/grab_pen_single/grab_pen_single}
CACHE_DIR=${CACHE_DIR:-/home/sen.wang/workspace/robotics/clear/data/cache_336}
DINO_CACHE_DIR=${DINO_CACHE_DIR:-/home/sen.wang/workspace/robotics/clear/data/dinov2_cache_336}
OUT_DIR=${OUT_DIR:-runs/v40_1_k6a6_statecf1_layered_v37_actionflow_smoke_b8_10}
STAGE1_CHECKPOINT=${STAGE1_CHECKPOINT:-runs/v40_1_k6a6_statecf1_norm_full_b8/checkpoints/best_contract.pt}
if [[ ! -f "${STAGE1_CHECKPOINT}" && -f "/home/sen.wang/workspace/robotics/clear/clearvla_v40_2/runs/v40_1_k6a6_statecf1_norm_full_b8/checkpoints/best_contract.pt" ]]; then
  STAGE1_CHECKPOINT=/home/sen.wang/workspace/robotics/clear/clearvla_v40_2/runs/v40_1_k6a6_statecf1_norm_full_b8/checkpoints/best_contract.pt
fi

python -u -m clearvla.cli.train_v40_policy \
  --data-root "${DATA_ROOT}" \
  --glob '*.hdf5' \
  --decoded-image-cache-dir "${CACHE_DIR}" \
  --cameras top wrist \
  --action-key action \
  --state-key qpos \
  --top-key observations/images/cam_high \
  --wrist-key observations/images/cam_right_wrist \
  --cache-resize 336 336 \
  --episode-split-mode ordered-counts \
  --train-episode-count 63 \
  --val-episode-count 5 \
  --test-episode-count 5 \
  --seed 0 \
  --batch-size 8 \
  --num-workers 4 \
  --normalizer zscore \
  --out-dir "${OUT_DIR}" \
  --stage1-checkpoint "${STAGE1_CHECKPOINT}" \
  --condition-mode dinov2-cache \
  --dinov2-model facebook/dinov2-base \
  --dinov2-token-cache-dir "${DINO_CACHE_DIR}" \
  --prefetch-dinov2-tokens \
  --dtype bf16 \
  --world-horizon 48 \
  --policy-horizon 24 \
  --segment-length 4 \
  --history-offsets=-8,-4,0 \
  --executed-action-offsets=-8,-4,-1 \
  --target-history-offsets=-8,-4,0 \
  --stride 1 \
  --hidden-size 512 \
  --heads 8 \
  --depth 8 \
  --midcut-layer 3 \
  --midcut-future-gain-init 0.1 \
  --layer-contract-adapters 1 \
  --layer-contract-adapter-dim 128 \
  --layer-contract-grad-scale 1.0 \
  --layer-contract-residual-scale 0.5 \
  --layer-shared-fm-probe 0 \
  --layer-fm-probe-hidden 256 \
  --layer-recurrent-consequence 1 \
  --layer-consequence-steps 6 \
  --layer-consequence-hidden 256 \
  --layer-consequence-delta-scale 1.0 \
  --layer-consequence-initial-gain 0.1 \
  --layer-causal-feedback-depth 0 \
  --layer-causal-memory-tokens 4 \
  --layer-low-causal-weight 1.0 \
  --layer-high-causal-weight 1.0 \
  --layer-low-latent-weight 1.0 \
  --layer-high-latent-weight 1.0 \
  --layer-causal-event-from-effect 1 \
  --layer-state-counterfactual 1 \
  --proposal-depth 2 \
  --proposal-dropout 0.25 \
  --dropout 0.05 \
  --event-tokens 3 \
  --canvas-registers 12 \
  --future-anchors 6 \
  --future-grid-size 4 \
  --action-basis-tokens 4 \
  --rollout-tail-start-step 8 \
  --rollout-tail-full-step 13 \
  --controlled-delta-rank 8 \
  --base-effect-hidden 128 \
  --latent-action-tokens 8 \
  --neutral-action-tokens 4 \
  --controlled-delta-dropout 0.0 \
  --role-dropout 0.1 \
  --visual-memory-dropout 0.0 \
  --canvas-dropout 0.0 \
  --inference-steps 5 \
  --gripper-dim-index -1 \
  --first-execution-steps 4 \
  --mid-execution-steps 8 \
  --physical-decode-delta-blend 0.25 \
  --final-action-decoder layered_residual_action_flow \
  --action-flow-residual-depth 4 \
  --action-flow-residual-high-slots 4 \
  --action-flow-residual-max-scale 0.15 \
  --action-flow-residual-visual-memory 1 \
  --action-flow-residual-context-memory 1 \
  --action-flow-residual-transition-memory 1 \
  --action-flow-residual-layer-memory 1 \
  --action-flow-residual-layer-pair-schedule 0:1,1:3,3:5,5:7 \
  --action-flow-residual-layer-detach 1 \
  --action-flow-residual-stage-router 1 \
  --action-flow-residual-anchor-memory 1 \
  --epochs 1 \
  --lr 8e-5 \
  --proposal-lr 5e-5 \
  --action-flow-residual-lr-scale 1.5 \
  --weight-decay 0.01 \
  --beta1 0.9 \
  --beta2 0.999 \
  --eps 1e-8 \
  --grad-clip 1.0 \
  --warmup-steps 500 \
  --min-lr-ratio 0.1 \
  --proposal-loss-weight 0.05 \
  --first-weight 1.5 \
  --first4-weight 1.3 \
  --first8-weight 1.15 \
  --tail-weight 1.1 \
  --event-loss-weight 0.08 \
  --event-positive-weight 4.0 \
  --event-focal-gamma 1.0 \
  --gripper-transition-l1-weight 0.06 \
  --smooth-delta-weight 0.02 \
  --decoded-action-loss-weight 0.08 \
  --physical-delta-consistency-weight 0.03 \
  --transition-gripper-flow-weight 0.06 \
  --event-delta-consistency-weight 0.03 \
  --event-magnitude-weight 0.03 \
  --event-off-delta-weight 0.03 \
  --arm-motion-loss-weight 0.03 \
  --arm-motion-threshold 0.02 \
  --gripper-event-threshold 0.1 \
  --deploy-min-recall 0.4 \
  --deploy-min-event-ratio 0.7 \
  --deploy-max-event-ratio 1.8 \
  --deploy-max-tail-first-ratio 2.6 \
  --eval-inference-steps 5 \
  --log-every 1 \
  --max-train-batches 10 \
  --max-val-batches 10 \
  --rollout-dynamics-loss-weight 0.03 \
  --rollout-delta-loss-weight 0.01 \
  --rollout-contrast-loss-weight 0.06 \
  --rollout-contrast-margin 0.02 \
  --future-latent-loss-weight 0.0 \
  --action-effect-loss-weight 0.0 \
  --future-latent-loss-start-epoch 1 \
  --future-latent-max-batches 0 \
  --memory-report-every 0 \
  --memory-report-detail 0 \
  --memory-report-sync 0 \
  --training-stage policy \
  --upper-lr-scale 0.20 \
  --midcut-head-lr-scale 1.0 \
  --midcut-aux-loss-weight 0.03 \
  --midcut-aux-final-ratio 0.15 \
  --midcut-aux-decay-epochs 4 \
  --midcut-rollout-dynamics-loss-weight 0.03 \
  --midcut-rollout-delta-loss-weight 0.01 \
  --midcut-rollout-contrast-loss-weight 0.03 \
  --contract-mode layer_adapter \
  --layer-contract-loss-weight 1.0 \
  --layer-contract-final-action-loss-weight 0.0 \
  --layer-contract-final-action-lr-scale 0.3 \
  --layerwise-lr-min-scale 0.3 \
  --layer-latent-loss-weight 1.0 \
  --layer-fm-probe-loss-weight 0.0 \
  --layer-event-loss-weight 0.05 \
  --layer-motion-loss-weight 0.03 \
  --layer-decoded-action-loss-weight 0.0 \
  --layer-contrast-loss-weight 0.03 \
  --layer-variance-loss-weight 0.05 \
  --layer-norm-loss-weight 0.02 \
  --layer-delta-match-loss-weight 0.15
