#!/usr/bin/env bash
# =============================================================================
# V59 CVAE-DIRECTION + TRANSFORMER MICRO
#
# Coarse query-spline direction writer is explicitly conditioned by the CVAE
# condition/z bias.  The micro path is no longer an MLP residual adapter: it is
# a token Transformer-style refinement block reusing the DiT/token route
# context, while CVAE intent stays in the coarse direction judgement.
#
# No process trajectory manifold, no smoothing loss, no gripper discretization.
# =============================================================================
set -euo pipefail

export OUT_DIR=${OUT_DIR:-runs/v59_cvae_direction_transformer_micro_b8}

export LATENT_CVAE_TRAJECTORY_DENOISE=${LATENT_CVAE_TRAJECTORY_DENOISE:-0}
export LATENT_CVAE_ARM_COEFF_OUTPUT=${LATENT_CVAE_ARM_COEFF_OUTPUT:-1}
export LATENT_CVAE_ARM_COEFF_POINTS=${LATENT_CVAE_ARM_COEFF_POINTS:-8}
export LATENT_CVAE_ARM_COEFF_BASIS=${LATENT_CVAE_ARM_COEFF_BASIS:-bspline}
export LATENT_CVAE_ARM_COEFF_DEGREE=${LATENT_CVAE_ARM_COEFF_DEGREE:-2}
export LATENT_CVAE_ARM_COEFF_RIDGE=${LATENT_CVAE_ARM_COEFF_RIDGE:-1e-2}
export LATENT_CVAE_ARM_COEFF_WRITER=${LATENT_CVAE_ARM_COEFF_WRITER:-query_direction}
export LATENT_CVAE_COEFF_INCLUDE_GRIPPER=${LATENT_CVAE_COEFF_INCLUDE_GRIPPER:-1}
export LATENT_CVAE_COEFF_MAGNITUDE_GROUPS=${LATENT_CVAE_COEFF_MAGNITUDE_GROUPS:-2}
export LATENT_CVAE_SPLINE_BASE_DIAGNOSTICS=${LATENT_CVAE_SPLINE_BASE_DIAGNOSTICS:-1}

export ADAPTIVE_CVAE_FUNCTION_ADAPTERS=${ADAPTIVE_CVAE_FUNCTION_ADAPTERS:-0}
export ADAPTIVE_CVAE_DETAIL_MICRO=${ADAPTIVE_CVAE_DETAIL_MICRO:-1}
export ADAPTIVE_CVAE_DETAIL_MICRO_SUPERVISION=${ADAPTIVE_CVAE_DETAIL_MICRO_SUPERVISION:-1}
export ADAPTIVE_CVAE_DETAIL_MICRO_SCALE=${ADAPTIVE_CVAE_DETAIL_MICRO_SCALE:-0.30}
export ADAPTIVE_CVAE_DETAIL_MICRO_GATE_INIT=${ADAPTIVE_CVAE_DETAIL_MICRO_GATE_INIT:-0.45}

export LATENT_CVAE_MICRO_SUPERVISION_WEIGHT=${LATENT_CVAE_MICRO_SUPERVISION_WEIGHT:-0.06}
export LATENT_CVAE_MICRO_EVENT_WEIGHT=${LATENT_CVAE_MICRO_EVENT_WEIGHT:-0.01}
export LATENT_CVAE_MICRO_MONOTONIC_WEIGHT=${LATENT_CVAE_MICRO_MONOTONIC_WEIGHT:-0.01}
export LATENT_CVAE_MICRO_WEIGHT_KL_WEIGHT=${LATENT_CVAE_MICRO_WEIGHT_KL_WEIGHT:-0.0005}
export LATENT_CVAE_MICRO_COVERAGE_SMOOTH_WEIGHT=${LATENT_CVAE_MICRO_COVERAGE_SMOOTH_WEIGHT:-0.001}
export LATENT_CVAE_MICRO_COVERAGE_FLOOR_WEIGHT=${LATENT_CVAE_MICRO_COVERAGE_FLOOR_WEIGHT:-0.001}
export LATENT_CVAE_MICRO_LEARNED_WEIGHT_MAX=${LATENT_CVAE_MICRO_LEARNED_WEIGHT_MAX:-0.35}
export LATENT_CVAE_MICRO_LEARNED_RAMP_STEPS=${LATENT_CVAE_MICRO_LEARNED_RAMP_STEPS:-2000}

SCRIPT_DIR="$(cd -- "$(dirname -- "${BASH_SOURCE[0]}")" && pwd)"
exec bash "${SCRIPT_DIR}/current_v54_rebase.sh" "$@"
