#!/usr/bin/env bash
# V85: recurrent multi-token controller plus detached candidate-operation gains.
set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"

export HIERARCHICAL_MMDIT_DEPTH="${HIERARCHICAL_MMDIT_DEPTH:-3}"
export HIERARCHICAL_MMDIT_REFINE_STEPS="${HIERARCHICAL_MMDIT_REFINE_STEPS:-$((2 * HIERARCHICAL_MMDIT_DEPTH))}"
export HIERARCHICAL_MMDIT_OPERATOR_STAGES="${HIERARCHICAL_MMDIT_OPERATOR_STAGES:-$((2 * HIERARCHICAL_MMDIT_DEPTH))}"
export HIERARCHICAL_MMDIT_CONTROL_TOKENS="${HIERARCHICAL_MMDIT_CONTROL_TOKENS:-8}"
export HIERARCHICAL_MMDIT_CONTROLLER_DEPTH="${HIERARCHICAL_MMDIT_CONTROLLER_DEPTH:-2}"
export HIERARCHICAL_MMDIT_CONTROLLER_HEADS="${HIERARCHICAL_MMDIT_CONTROLLER_HEADS:-8}"
export HIERARCHICAL_MMDIT_CONTROLLER_FFN_EXPANSION="${HIERARCHICAL_MMDIT_CONTROLLER_FFN_EXPANSION:-2.0}"
export HIERARCHICAL_MMDIT_OPERATION_CANDIDATE_PROBES="${HIERARCHICAL_MMDIT_OPERATION_CANDIDATE_PROBES:-1}"
export HIERARCHICAL_MMDIT_OPERATION_ROUTE_LOSS_WEIGHT="${HIERARCHICAL_MMDIT_OPERATION_ROUTE_LOSS_WEIGHT:-0.05}"
export HIERARCHICAL_MMDIT_OPERATION_ROUTE_TEMPERATURE="${HIERARCHICAL_MMDIT_OPERATION_ROUTE_TEMPERATURE:-0.5}"
export HIERARCHICAL_MMDIT_OPERATION_ROUTE_WARMUP_STEPS="${HIERARCHICAL_MMDIT_OPERATION_ROUTE_WARMUP_STEPS:-0}"
export HIERARCHICAL_MMDIT_CONTROLLER_LR_SCALE="${HIERARCHICAL_MMDIT_CONTROLLER_LR_SCALE:-1.0}"
export HIERARCHICAL_MMDIT_EXHAUSTION_MODE="${HIERARCHICAL_MMDIT_EXHAUSTION_MODE:-learned_shadow}"
export OUT_DIR="${OUT_DIR:-runs/v85_unified_controller_d${HIERARCHICAL_MMDIT_DEPTH}_r${HIERARCHICAL_MMDIT_REFINE_STEPS}_c${HIERARCHICAL_MMDIT_CONTROL_TOKENS}_h${HIERARCHICAL_MMDIT_CONTROLLER_HEADS}}"

printf '[v85] controller_tokens=%s controller_depth=%s controller_heads=%s refine_depth=%s steps=%s stages=%s operation_route_weight=%s eval_route=%s\n' \
  "${HIERARCHICAL_MMDIT_CONTROL_TOKENS}" \
  "${HIERARCHICAL_MMDIT_CONTROLLER_DEPTH}" \
  "${HIERARCHICAL_MMDIT_CONTROLLER_HEADS}" \
  "${HIERARCHICAL_MMDIT_DEPTH}" \
  "${HIERARCHICAL_MMDIT_REFINE_STEPS}" \
  "${HIERARCHICAL_MMDIT_OPERATOR_STAGES}" \
  "${HIERARCHICAL_MMDIT_OPERATION_ROUTE_LOSS_WEIGHT}" \
  "${HIERARCHICAL_MMDIT_EXHAUSTION_MODE}"

exec bash "${SCRIPT_DIR}/current_v82_sidecar_nested_contraction.sh" \
  --hierarchical-mmdit-unified-controller 1 \
  --hierarchical-mmdit-control-tokens "${HIERARCHICAL_MMDIT_CONTROL_TOKENS}" \
  --hierarchical-mmdit-controller-depth "${HIERARCHICAL_MMDIT_CONTROLLER_DEPTH}" \
  --hierarchical-mmdit-controller-heads "${HIERARCHICAL_MMDIT_CONTROLLER_HEADS}" \
  --hierarchical-mmdit-controller-ffn-expansion \
    "${HIERARCHICAL_MMDIT_CONTROLLER_FFN_EXPANSION}" \
  --hierarchical-mmdit-operation-candidate-probes \
    "${HIERARCHICAL_MMDIT_OPERATION_CANDIDATE_PROBES}" \
  --hierarchical-mmdit-schedule-mode fixed \
  --hierarchical-mmdit-exhaustion-mode "${HIERARCHICAL_MMDIT_EXHAUSTION_MODE}" \
  --hierarchical-mmdit-oracle-route-loss-weight 0 \
  --hierarchical-mmdit-operation-route-loss-weight \
    "${HIERARCHICAL_MMDIT_OPERATION_ROUTE_LOSS_WEIGHT}" \
  --hierarchical-mmdit-operation-route-temperature \
    "${HIERARCHICAL_MMDIT_OPERATION_ROUTE_TEMPERATURE}" \
  --hierarchical-mmdit-operation-route-warmup-steps \
    "${HIERARCHICAL_MMDIT_OPERATION_ROUTE_WARMUP_STEPS}" \
  --hierarchical-mmdit-controller-lr-scale \
    "${HIERARCHICAL_MMDIT_CONTROLLER_LR_SCALE}" \
  "$@"
